### ISSUE TITLE
Latest version now showing up in menu

### ISSUE THREAD

**Issue by weiweihuanghuang** [mekkablue/ShowAngledHandles#10]
For Glyphs Version 2.3b (839)? I installed the one that doesn't have 'old' in it's name.

**Comment by mekkablue** [comment]
839 is not the latest version. What exactly is the problem?

**Comment by weiweihuanghuang** [comment]
I can't activate it, as it's not appearing in the menu.

**Comment by weiweihuanghuang** [comment]
Works now in updated Glyphs app
