### ISSUE TITLE
setDefaultLineWidth_

### ISSUE THREAD

**Issue by Mark2Mark** [mekkablue/ShowAngledHandles#12]
There seems to be an issue with setting the (default?) line width.
The plugin reverses up the Glyphs built-in measurement with according to the zoom. The farther you zoom out, the fatter the line gets.
I sent a screencast to info at g_app. Do you recieve mails from there or should i send it somewhere else?

**Comment by mekkablue** [comment]
support at… reaches me too, or res at… goes to me directly.

**Comment by Mark2Mark** [comment]
sent.

**Comment by mekkablue** [comment]
Thx. The latest update should fix this.
