### ISSUE TITLE
Show Angled Handles

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/ShowAngledHandles#14]
G2 Build 1101-1105.
Just noticed that Show Angled Handles has lost its color (red) on most control points. It shows up on a few but most are just white now. Not sure if it started with today's update of the plugin (01/08) but I think it did.

**Comment by mekkablue** [comment]
Right Click, and in the context menu uncheck _Mark handles only if they are almost straight._

**Comment by mekkablue** [comment]
I see there was a bug in the code. Just uploaded a fix. Thx for reporting & sorry for inconvenience.
