### ISSUE TITLE
Plugin slows down Glyphs in Mojave

### ISSUE THREAD

**Issue by designiq** [mekkablue/ShowAngledHandles#15]
My combination is Version 2.5.2 (1169) + macOS Mojave 10.14 (18A391). In this environment ShowAngledHandles slows down all operations in Glyphs. Even selecting a node takes a second or two.

**Comment by mekkablue** [comment]
Have you tried 1171 yet?

**Comment by designiq** [comment]
Yes, it is significantly faster. Still not as fast as without the plugin, the behaviour of Glyphs is little bit slower. But almost perfect.

**Comment by mekkablue** [comment]
Python plug-ins always slow down performance. Rewriting _Show Angled Handles_ in ObjC is on my list, but will take a while.
