### ISSUE TITLE
Not flagging crossed handles

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/ShowAngledHandles#16]
macOS 10.12.6, G2.6.1 [1204] -- IIRC the plugin used to show all instances of crossing handles, but when the two on-curve nodes are at an angle to each other it now only shows them when one crosses very near to the off-curve node of the other. If it crosses a few units away it isn't flagged.

The image shows an example of when it isn't flagging an obvious cross.
![screen shot 2019-01-20](https://user-images.githubusercontent.com/2348503/51481034-4e548400-1d58-11e9-81a5-044511646a0d.png)

**Comment by mekkablue** [comment]
Did you turn on the option in the context menu?

**Comment by LibertyType** [comment]
Everything on except last one for "almost straight" paths. I should have noted previously that in the provided image if the top handle were angled closer to the horizontal handle, it would have been flagged.

**Comment by LibertyType** [comment]
A follow-up: the plugin now appears to be working consistently as it should. I have no clue at this point why, but will try to pay closer attention if it happens again as to what may have triggered it.

**Comment by mekkablue** [comment]
Can you send me or post the glyph?

**Comment by LibertyType** [comment]
Sent to support email to your attention.

**Comment by mekkablue** [comment]
Hmm. I cannot reproduce the issue. It works as expected for me. Is there an error message in the Macro Window when it happens to you?

**Comment by LibertyType** [comment]
I just discovered some interesting oddities. After moving the entire glyph 100 units, suddenly the Angled Handle warning worked again but only for the top example on the left.

So I played around with moving nodes and discovered on the bottom example that if I moved the on-curve node on the angled path vertically by a unit or two I could trigger the warning, but if instead I moved the left off-curve node on the horizontal it will not trigger the warning.

**Comment by LibertyType** [comment]
I finally captured some feedback from the Macro Panel which may relate to this problem.

Traceback (most recent call last):
  File "GlyphsApp/GlyphsApp/plugins.py", line 1158, in drawForegroundForLayer_options_
  File "plugin.py", line 104, in foreground
  File "plugin.py", line 175, in drawCrossingsForData
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/PyObjC/objc/_convenience.py", line 459, in __getitem__objectAtIndex_
    raise IndexError("list index out of range")
IndexError: list index out of range

**Comment by mekkablue** [comment]
Thanks, I’ll have a look.

**Comment by LibertyType** [comment]
I believe this problem has been fixed some time ago so will close it.
