### ISSUE TITLE
Non-straight lines not highlighted anymore

### ISSUE THREAD

**Issue by everdrone** [mekkablue/ShowAngledHandles#18]
The only feature that seems to be working now is the actual handle dot being red when not aligned, all the other highlights disappeared, tried reinstalling but the issue still occurs.

Radio silence in the macro panel too.

How can I help you help me?

**Comment by mekkablue** [comment]
You need to turn on/off the respective settings in the context menu.

All these settings should be on by default though. The plug-in registers no defaults currently.

**Comment by mekkablue** [comment]
The defaults should work again, I hope. But in your case, simply open the context menu and set your desired options.
