### ISSUE TITLE
Visual Indicator missing

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/ShowAngledHandles#19]
Before the rewrite the plugin had visual indicators as shown by the mockup attached, i.e. the dotted line shown. 

That is now missing, and since I found it very helpful I am asking that it be restored.
<img width="150" alt="Indicator" src="https://user-images.githubusercontent.com/2348503/63028653-dcb76100-be74-11e9-99ad-12b1a4c7e9f2.png">

**Comment by mekkablue** [comment]
That is fixed already. Uninstall and reinstall the plug-in and restart Glyphs.
