### ISSUE TITLE
New Binary

### ISSUE THREAD

**Issue by LibertyType** [mekkablue/ShowAngledHandles#21]
Is a new binary file coming soon on this or for upgrade reasons does it need to wait a bit longer?

**Comment by mekkablue** [comment]
What is the issue? Is it not working? In which version of Glyphs?

**Comment by LibertyType** [comment]
3.0b. Georg did some work on it but said you needed to create a new binary. I'm having the same issue I first reported in the 3.0b Plugin thread, i.e. it will not stay activated in a character window. It will stay activated in Font view but as soon as any character is opened, it deactivates.

**Comment by mekkablue** [comment]
Just uploaded build 44. It works for me now in Glyphs 2 (1313) and 3 (1317).
