### ISSUE TITLE
Plugin not loading Glyphs 2.2.2, SAH 1.1.1

### ISSUE THREAD

**Issue by robmck** [mekkablue/ShowAngledHandles#6]
Updated ShowAngledHandles to 1.1.1, and the plugin doesn't appear to be loading - doesn't appear in the menu nor does Cmd-Y do anything (except for the pleasant Bong error sound). Everything looks good in the Plugins directory, and other plugins run.

Glyphs 2.2.2 (827).

Ideas (or hints for debugging)?

**Comment by mekkablue** [comment]
I cannot reproduce it. Everything works as expected for me in Version 2.2.2 (827). Perhaps a conflict with other plugins: disable them all except ShowAngledHandles, and try again.

If there is a problem with the plugin, you should see messages in the Macro window and the Console when you start Glyphs.

**Comment by robmck** [comment]
Uninstalled all plugins, then reinstalled all, seems to be happy now.
